[bar]
background       = "#0f131c"
background-alpha = 0.0
text             = "#dfe2ef"
active           = "#f9515d"
scale-with-font  = true
size-horizontal  = 29
size-vertical    = 28
float-margin     = 0
float-radius     = 12
capsule          = "#1c2029"
capsule-alpha    = 0.8
padding-scale    = 1.2
font-size        = 14
icon-font        = 15
icon-canvas      = 18
icon-slot        = 30
